package com.factor.launcher.util

object Constants
{
    const val PACKAGE_NAME = "com.factor.launcher"

    const val BROADCAST_ACTION_REMOVE = "$PACKAGE_NAME.ACTION_REMOVE"

    const val REMOVE_KEY = "$PACKAGE_NAME.KEY_REMOVE"

    const val NOTIFICATION_INTENT_ACTION_POST = "$PACKAGE_NAME.NOTIFICATION_ACTION_POST"

    const val NOTIFICATION_INTENT_ACTION_CLEAR = "$PACKAGE_NAME.NOTIFICATION_ACTION_CLEAR"

    const val NOTIFICATION_INTENT_PACKAGE_KEY = "$PACKAGE_NAME.NOTIFICATION_PACKAGE_KEY"

    const val NOTIFICATION_INTENT_TICKER_TEXT_KEY = "$PACKAGE_NAME.NOTIFICATION_TICKER_TEXT_KEY"
}