package com.factor.launcher.util

//constant values
object Constants
{
    const val PACKAGE_NAME = "com.factor.launcher"

    const val SYSTEM_DIALOG_REASON_HOME_KEY = "homekey"

    const val SYSTEM_DIALOG_REASON_KEY = "reason"

    const val STORAGE_PERMISSION_CODE = 955

    const val BROADCAST_ACTION_ADD = "$PACKAGE_NAME.ACTION_ADD"

    const val BROADCAST_ACTION_REMOVE = "$PACKAGE_NAME.ACTION_REMOVE"

    const val BROADCAST_ACTION_RENAME = "$PACKAGE_NAME.ACTION_RENAME"

    const val BROADCAST_ACTION_RECENT = "$PACKAGE_NAME.ACTION_RECENT"

    const val ADD_KEY = "$PACKAGE_NAME.KEY_ADD"

    const val REMOVE_KEY = "$PACKAGE_NAME.KEY_REMOVE"

    const val RENAME_KEY = "$PACKAGE_NAME.KEY_RENAME"

    const val NOTIFICATION_INTENT_ACTION_POST = "$PACKAGE_NAME.NOTIFICATION_ACTION_POST"

    const val NOTIFICATION_INTENT_ACTION_CLEAR = "$PACKAGE_NAME.NOTIFICATION_ACTION_CLEAR"

    const val NOTIFICATION_INTENT_PACKAGE_KEY = "$PACKAGE_NAME.NOTIFICATION_PACKAGE_KEY"

    const val NOTIFICATION_INTENT_CONTENT_TEXT_KEY = "$PACKAGE_NAME.NOTIFICATION_CONTENT_TEXT_KEY"

    const val NOTIFICATION_INTENT_CATEGORY_KEY = "$PACKAGE_NAME.NOTIFICATION_CATEGORY_KEY"

    const val NOTIFICATION_INTENT_TITLE_TEXT_KEY = "$PACKAGE_NAME.NOTIFICATION_TITLE_TEXT_KEY"

    const val NOTIFICATION_INTENT_ID_KEY = "$PACKAGE_NAME.NOTIFICATION_ID_KEY"

    const val SETTINGS_CHANGED = "$PACKAGE_NAME.SETTINGS_CHANGED"

    const val WIDGET_HOST_ID = 559

    const val WIDGET_KEY = "$PACKAGE_NAME.REQUEST_PICK_WIDGET"

    const val WIDGET_RESULT_KEY = "$PACKAGE_NAME.WIDGET_RESULT"

    const val REQUEST_CREATE_WIDGET = 69

    const val REQUEST_BIND_WIDGET = 68

    const val REQUEST_PICK_WIDGET = 67
}